### ISSUE TITLE
Image upload hk.

### ISSUE THREAD

**Issue by seymafirat** [abdurrahmanekr/nodejs-upload-example#1]
Merhabalar,
React nativede galeriden seçtiğim fotoğrafı 2 sayfa sonrasına açıklamalarla beraber gönderip ordaki tüm bilgileri web servise aktarmak istiyorum. Fakat  tüm bilgileri listeliyorum, atarken resim null dönüyor. Normalde const resim değişkeni oluşturuyordum galeriden seçtiğim resimler için. Şimdi bunu nasıl yapacağım? const res = getParam('resim'); şu şekilde bir önceki sayfadan resmi alıp flatlistte gösteriyorum.  Hatalı bir kullanım yapıyorum sanırım, bir bakabilir misiniz? 
 const resim = {
      uri: res.uri,
      //type: res.mime,
      name: res.fileName,
    };
    formData.append('resim', resim);

![Screenshot_1621796763](https://user-images.githubusercontent.com/57031770/119273338-1c4ad980-bc13-11eb-9b17-f94ab2fa94b6.png)

**Comment by abdurrahmanekr** [comment]
name kısmı boş gönderiliyor olabilir mi?

**Comment by seymafirat** [comment]
resim için mi? sanırım resmin parametreleriyle alakalı bir problem var fakat nasıl çözeceğimi anlamadım
![11](https://user-images.githubusercontent.com/57031770/119330246-adab6180-bc8e-11eb-985d-54debfca6193.JPG)

**Comment by abdurrahmanekr** [comment]
Aslında resim atma işi basit, hangi sayfaya paslarsanız paslayın elinizde path, name ve type bilgileri varsa upload edebilirsiniz. Postman'den aşağıdaki gibi göndermeyi başarabiliyorsanız:

![image](https://user-images.githubusercontent.com/15075759/119346484-f0773480-bca2-11eb-8cdc-a747e11421d2.png)

`resim` değişkeni de sizinki gibi olursa:
```javascript
// form data türündeki dosya verisi
const resim = {
  uri : response.uri, // dosyanın yolu
  type: response.type, // dosyanın mimeType değeri
  name: response.fileName || 'resim.png', // dosyanın ismi
};
```

Sonrası için: 
```javascript
let formdata = new FormData();
formdata.append('file', resim);

// Sunucuya yükleme işlemi buradan oluyor
fetch('http://localhost:8080/upload', {
  method: 'PUT',
  body: formdata,
  headers: {
    'Content-Type': 'multipart/form-data', // Bu değeri vermek önemli!
    'Accept': 'application/json',
  },
})
.then(res => {
  console.log('başarılı', res)
})
.catch(err => {
  console.error(err);
});
```

Şeklinde yapabilmeniz lazım. Eğer bir şeylerin yanlış olduğunu düşünüyorsanız ancak debug ile bulabilirsiniz diye düşünüyorum

**Comment by seymafirat** [comment]
Çok teşekkür ederim, bir sorum daha olacak sizin kodunuzdan yararlanıyorum da galeriden aldığım resmi flatlistte göstermek için this.state.response yapmam gerekmiyor mu veya this.state.resim? İkisini yazınca da gösteremedim de

**Comment by abdurrahmanekr** [comment]
Rica ederim. Ekranda göstermek istiyorsanız state'i kullanabilirsiniz. Attığım kodda onu eklemedim. Sonuçta bu bir istek yani gönder butonuna basmak gerekiyor. İstekten önce kişinin seçtiği resmi state kullanarak gösterebilirisiniz, size kalmış.

**Comment by seymafirat** [comment]
tamamdır çok teşekkür ederim ilgilendiğiniz için. iyi günler

**Comment by abdurrahmanekr** [comment]
Rica ederim size de iyi, sağlıklı günler
